// Copyright (c) 2019-2020 FRC Team 3512. All Rights Reserved.

#include <cstdio>
#include <string_view>

#include <frc/Filesystem.h>
#include <gtest/gtest.h>
#include <wpi/FileSystem.h>
#include <wpi/SmallString.h>

#include "Robot.hpp"

void DeleteSubsystemCSV(const wpi::SmallVectorImpl<char>& path,
                        std::string_view filename) {
    int version = 0;
    while (wpi::sys::fs::exists(path + "/" + filename.data() +
                                std::to_string(version))) {
        version++;
    }

    if (version > 0) {
        std::remove((path + "/" + filename.data() + std::to_string(version - 1))
                        .str()
                        .c_str());
    }
}

// Make sure robot initializes
TEST(RobotTest, Init) {
    frc3512::Robot robot;

    // Delete empty CSV files generated by robot subsystems
    wpi::SmallString<64> path;
    frc::filesystem::GetOperatingDirectory(path);

    DeleteSubsystemCSV(path, "Climber.csv");
    DeleteSubsystemCSV(path, "ClimberStuff.csv");
    DeleteSubsystemCSV(path, "DriveErrorCov.csv");
    DeleteSubsystemCSV(path, "DrivePositions.csv");
    DeleteSubsystemCSV(path, "DriveVelocities.csv");
    DeleteSubsystemCSV(path, "DriveVoltages.csv");
    DeleteSubsystemCSV(path, "Elevator.csv");
    DeleteSubsystemCSV(path, "FourBarLift.csv");
    std::remove((path + "/Robot.log").str().c_str());
}
